### ISSUE TITLE
No README file when trying to poetry install the dependencies 

### ISSUE THREAD

**Issue by Arstanley** [T1aNS1R/Evil-Geniuses#1]
There is no README defined inside the Evil_Geniuses folder which results in the following error 

`The current project could not be installed: [Errno 2] No such file or directory: '/home/Projects/Evil-Geniuses/Evil_Geniuses/README.md'
If you do not want to install the current project use --no-root`

**Comment by T1aNS1R** [comment]
Thanks for the reminder, we have uploaded the reademe file
